name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, mbstring, redis, bcmath, soap

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: intl mbstring redis bcmath soap
        env:
          COMPOSER_AUTH: '{"http-basic": {"spark.laravel.com": {"username": "${{ secrets.SPARK_USERNAME }}", "password": "${{ secrets.SPARK_API_PASSWORD }}" }} }'
      - name: Create Directories
        run: mkdir -p storage/framework/cache  && mkdir -p storage/framework/views && mkdir -p storage/framework/sessions
      - name: Directory Permissions
        run: sudo chmod -R 777 storage/ bootstrap/cache
      - name: Install NPM
        run: npm install && npm run build
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: |
          touch database/database.sqlite
          php artisan migrate
      - name: Clear caches
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
      - name: PHPUnit Tests
        run: |
          ./vendor/bin/pest
      - name: Static analysis
        run: ./bin/phpstan
      - name: PSR
        run: ./bin/style --dry-run
